



GET http://localhost:5000/leases/ledger?start_date=2021-03-28T00:00:00.000Z&end_date=2021-05-27T00:00:00.000Z&frequency=WEEKLY&weekly_rent=555
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidXNlclJpZ2h0cyI6WyJhZG1pbiJdLCJpYXQiOjE2M=TgwNTA4NDcsImV4cCI6MTYxODA1MjY0N30.Ainyt2T5yvD7_oSDJcRwAldXXmbIocjGbJisyHlUkPc